services:
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments: [@mailer, 50]
        calls:
            - [ setLocale, [ %locale% ] ]
        tags:
            -  { name: twig.extension }

    oc_platform.ckeditor:
        class: OC\PlatformBundle\Form\Type\CkeditorType
        tags:
            - { name: form.type, alias: ckeditor }

    oc_platform.beta.html:
        class: OC\PlatformBundle\Beta\BetaHTML

    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments: [@oc_platform.beta.html, "2014-12-31"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }


